# https://projecteuler.net/problem=12

"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

def triangle_num(n)->int:
    return int(n*(n+1)/2)

def divisors(n):
    divs = set()
    for i in range(1, n//4 + 1):
        if n%i == 0:
            divs.add(i)
            divs.add(n/i)
    divs.add(n)
    return divs

if __name__ == "__main__":
    div_counter = 0
    i = 1
    while div_counter!=500:
        t= triangle_num(i)
        div_counter = len(divisors(t))
        print(f"{t}: {div_counter}")
        i+=1

    print(f"solution: {t}")